name: Publish Docker image

on:
  push:
    tags: 
      - "v*.*"
      
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.docker_build }}
          
      - name: Login in Docker-Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
#            ghcr.io/svvsvv/docker_build:1
            svvsvv/docker_build:${{ github.sha }}
            svvsvv/docker_build:${{ github.run_number }}
            
      - name: Notification in Slack
        uses: rtCamp/action-slack-notify@v2
        if: success()
        env:
          SLACK_CHANNEL: github_notifications
          SLACK_COLOR: 'green'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Image was succesfully pushed.'
          SLACK_TITLE: Details
          SLACK_USERNAME: Vitali Snisar
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          
      - name: Notification in Slack [rejection]
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_CHANNEL: github_notifications
          SLACK_COLOR: 'red'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'Image was succesfully pushed.'
          SLACK_TITLE: Details
          SLACK_USERNAME: Vitali Snisar
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
